title: Alexander Kriwoluzky
baseURL: 'https://www.alexanderkriwoluzky.com/'
copyright: '© Alexander Kriwoluzky 2024'

defaultContentLanguage: en
hasCJKLanguage: false

module:
  imports:
    - path: github.com/HugoBlox/kit/templates/academic-cv
