[build]
  publish = "public"
  command = "hugo"

[build.environment]
  GIT_SUBMODULE_STRATEGY = "recursive"

[context.production.environment]
  HUGO_VERSION = "0.58.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"